### PR TITLE
remove AKS documentation

### PR DESCRIPTION
**Pull request by jackfrancis**
This PR removes reference matter about using kamino on AKS. Based on testing today it appears that changes to the CSE implementation overwrite image updates. This newly observed Azure Extension appears to play a role in ensuring that updates to the VMSS imageReference aren't sticky at provision time:

```
{
    "name": "AKSLinuxExtension",
    "properties": {
        "autoUpgradeMinorVersion": false,
        "provisionAfterExtensions": [
            "vmssCSE"
        ],
        "suppressFailures": false,
        "publisher": "Microsoft.AKS",
        "type": "Compute.AKS.Linux.AKSNode",
        "typeHandlerVersion": "1.26"
    }
}
```

E.g., even a change like this to the storageProfile by kamino does not result in new nodes coming online w/ the characteristics of the OS that correlate with the OS image that was used to create the SIG image:

```
            "storageProfile": {
                "osDisk": {
                    "osType": "Linux",
                    "createOption": "FromImage",
                    "caching": "ReadWrite",
                    "managedDisk": {
                        "storageAccountType": "Premium_LRS"
                    },
                    "diskSizeGB": 30
                },
                "imageReference": {
                    "id": "/subscriptions/aa3d3369-e814-4495-899d-d31e8d7d09ce/resourceGroups/MC_capz-e2e-51tjn8-aks_capz-e2e-51tjn8-aks_eastus/providers/Microsoft.Compute/galleries/SIG_MC_capz_e2e_51tjn8_aks_capz_e2e_51tjn8_aks_eastus/images/kamino-aks-pool0-16158696-vmss-prototype"
                }
            },
```

### CODE REVIEW

**Comment by jackfrancis** [comment]
cc @alexeldeib @juan-lee

Nothing for you to do here, just FYI that the kamino prototype I showed you a while back is no longer a thing.

**Comment by Michael-Sinz** [comment]
Sad...

**Review by Michael-Sinz — APPROVED** [review]
Sad but yet another reason AKS and Skyman are unlikely to become unified.

**Comment by Michael-Sinz** [comment]
Well, I have now been using Skyman on AKS and there are still some problems but if you don't ask AKS to do the scaling of the node pools it will not overwrite - I think I will make an updated test and show how that can be done.  (Assuming I have free time anytime soon)

**Pull request merged**
